spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_6ed3de57573502d?reconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: b237be3261e07e
    password: f175685f
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#   properties:
#      hibernate:
#        dialect:org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: ${PORT:8080}